package org.lpld.datacompanies.backend.model;

public class AnnualAccountStringHelper {
    
    public int ACTIF;

    public int CAPITAL_SOUSCRIT_NON_APPELE;

    public int FRAIS_D_ETABLISSEMENT;

    public int FRAIS_DE_DEVELOPPEMENT_OU_DE_RECHERCHE_ET_DEVELOPPEMENT;

    public int CONCESSIONS_BREVETS_ET_DROITS_SIMILAIRES;

    public int FONDS_COMMERCIAL;

    public int AUTRES_IMMOBILISATIONS_INCORPORELLES;

    public int AVANCES_ET_ACOMPTES_SUR_IMMOBILISATIONS_INCORPORELLES;

    public int TERRAINS;

    public int CONSTRUCTIONS;

    public int INSTALLATIONS_TECHNIQUES_MATERIEL_ET_OUTILLAGE_INDUSTRIELS;

    public int AUTRES_IMMOBILISATIONS_CORPORELLES;

    public int IMMOBILISATIONS_EN_COURS;

    public int AVANCES_ET_ACOMPTES;

    public int PARTICIPATIONS_EVALUEES_MISE_EN_EQUIVALENCE;

    public int AUTRES_PARTICIPATIONS;

    public int CREANCES_RATTACHEES_A_DES_PARTICIPATIONS;

    public int AUTRES_TITRES_IMMOBILISES;

    public int PRETS;

    public int AUTRES_IMMOBILISATIONS_FINANCIERES;

    public int TOTAL_I;

    public int MATIERES_PREMIERES_APPROVISIONNEMENTS;

    public int EN_COURS_DE_PRODUCTION_DE_BIENS;

    public int EN_COURS_DE_PRODUCTION_DE_SERVICES;

    public int PRODUITS_INTERMEDIAIRES_ET_FINIS;

    public int MARCHANDISES;

    public int AVANCES_ET_ACOMPTES_VERSES_SUR_COMMANDES;

    public int CLIENTS_ET_COMPTES_RATTACHES;

    public int AUTRES_CREANCES;

    public int CAPITAL_SOUSCRIT_ET_APPELE_NON_VERSE;

    public int VALEURS_MOBILIERES_DE_PLACEMENT;

    public int DISPONIBILITES;

    public int CHARGES_CONSTATEES_D_AVANCE;

    public int TOTAL_II;

    public int CHARGES_A_REPARTIR_OU_FRAIS_D_EMISSION_D_EMPRUNT;

    public int PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS_IV;

    public int ECARTS_DE_CONVERSION_ACTIF_V;

    public int TOTAL_GENERAL_0_A_V;

    public int PARTS_A_MOINS_D_UN_AN;

    public int PARTS_A_PLUS_D_UN_AN;

    public int PASSIF;

    public int CAPITAL_SOCIAL_OU_INDIVIDUEL;

    public int PRIMES_D_EMISSION_DE_FUSION_D_APPORT_;

    public int DONT_ECART_D_EQUIVALENCE;

    public int ECARTS_DE_REEVALUATION;

    public int RESERVE_LEGALE_1;

    public int RESERVES_STATUTAIRES_OU_CONTRACTUELLES;

    public int DONT_RESERVE_SPECIALE_DES_PROVISIONS_POUR_FLUCTUATION_DES_COURS;

    public int RESERVES_REGLEMENTEES_1;

    public int DONT_RESERVE_RELATIVE_A_L_ACHAT_D_OEUVRES_ORIGINALES_D_ARTISTES_VIVANTS;

    public int AUTRES_RESERVES;

    public int REPORT_A_NOUVEAU;

    public int RESULTAT_DE_L_EXERCICE_BENEFICE_OU_PERTE;

    public int SUBVENTIONS_D_INVESTISSEMENT;

    public int PROVISIONS_REGLEMENTEES;

    public int PRODUIT_DES_EMISSIONS_DE_TITRES_PARTICIPATIFS;

    public int AVANCES_CONDITIONNEES;

    public int PROVISIONS_POUR_RISQUES;

    public int PROVISIONS_POUR_CHARGES;

    public int TOTAL_III;

    public int EMPRUNTS_OBLIGATAIRES_CONVERTIBLES;

    public int AUTRES_EMPRUNTS_OBLIGATAIRES;

    public int EMPRUNTS_ET_DETTES_AUPRES_DES_ETABLISSEMENTS_DE_CREDIT_3;

    public int EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS_4;

    public int AVANCES_ET_ACOMPTES_RECUS_SUR_COMMANDES_EN_COURS;

    public int DETTES_FOURNISSEURS_ET_COMPTES_RATTACHES;

    public int DETTES_FISCALES_ET_SOCIALES;

    public int DETTES_SUR_IMMOBILISATIONS_ET_COMPTES_RATTACHES;

    public int AUTRES_DETTES;

    public int PRODUITS_CONSTATES_D_AVANCE_2;

    public int TOTAL_IV;

    public int V;

    public int TOTAL_GENERAL_I_A_V;

    public int DONT_RESERVE_REGLEMENTEE_DES_PLUSVALUES_A_LONG_TERME;

    public int DETTES_ET_PRODUITS_CONSTATES_D_AVANCE_A_MOINS_D_UN_AN;

    public int DONT_CONCOURS_BANCAIRES_COURANTS_ET_SOLDES_CREDITEURS_DE_BANQUES_ET_CCP;

    public int DONT_EMPRUNTS_PARTICIPATIFS;

    public int COMPTE_DE_RESULTAT_A;

    public int VENTES_DE_MARCHANDISES;

    public int PRODUCTION_VENDUE_BIENS;

    public int PRODUCTION_VENDUE_SERVICES;

    public int CHIFFRES_D_AFFAIRES_NETS;

    public int PRODUCTION_STOCKEE;

    public int PRODUCTION_IMMOBILISEE;

    public int SUBVENTIONS_D_EXPLOITATION;

    public int REPRISES_SUR_AMORTISSEMENTS_ET_PROVISIONS_TRANSFERT_DE_CHARGES;

    public int AUTRES_PRODUITS;

    public int TOTAL_DES_PRODUITS_D_EXPLOITATION_I;

    public int ACHATS_DE_MARCHANDISES_Y_COMPRIS_DROITS_DE_DOUANE;

    public int VARIATION_DE_STOCK_MARCHANDISES;

    public int ACHATS_DE_MATIERES_PREMIERES_ET_AUTRES_APPROVISIONNEMENTS;

    public int VARIATION_DE_STOCK_MATIERES_PREMIERES_ET_APPROVISIONNEMENTS;

    public int AUTRES_ACHATS_ET_CHARGES_EXTERNES;

    public int IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;

    public int SALAIRES_ET_TRAITEMENTS;

    public int CHARGES_SOCIALES;

    public int DOT_D_EXPLOIT_DOTATIONS_AUX_AMORTISSEMENTS;

    public int DOT_D_EXPLOIT_DOTATIONS_AUX_PROVISIONS;

    public int DOT_D_EXPLOIT_SUR_ACTIF_CIRCULANT_DOTATIONS_AUX_PROVISIONS;

    public int DOT_D_EXPLOIT_POUR_RISQUES_ET_CHARGES_DOTATIONS_AUX_PROVISIONS;

    public int AUTRES_CHARGES;

    public int TOTAL_DES_CHARGES_D_EXPLOITATION_II;

    public int RESULTAT_D_EXPLOITATION_I_II;

    public int BENEFICE_ATTRIBUE_OU_PERTE_TRANSFEREE_III;

    public int PERTE_SUPPORTEE_OU_BENEFICE_TRANSFERE_IV;

    public int PRODUITS_FINANCIERS_DE_PARTICIPATIONS;

    public int PRODUITS_DES_AUTRES_VALEURS_MOBILIERES_ET_CREANCES_DE_L_ACTIF_IMMOBILISE;

    public int AUTRES_INTERETS_ET_PRODUITS_ASSIMILES;

    public int REPRISES_SUR_PROVISIONS_ET_TRANSFERTS_DE_CHARGES;

    public int DIFFERENCES_POSITIVES_DE_CHANGE;

    public int PRODUITS_NETS_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;

    public int TOTAL_DES_PRODUITS_FINANCIERS_V;

    public int DOTATIONS_FINANCIERES_SUR_AMORTISSEMENTS_ET_PROVISIONS;

    public int INTERETS_ET_CHARGES_ASSIMILEES;

    public int DIFFERENCES_NEGATIVES_DE_CHANGE;

    public int CHARGES_NETTES_SUR_CESSIONS_DE_VALEURS_MOBILIERES_DE_PLACEMENT;

    public int TOTAL_DES_CHARGES_FINANCIERES_VI;

    public int RESULTAT_FINANCIER_V_VI;

    public int RESULTAT_COURANT_AVANT_IMPOTS_I_II_III_IV_V_VI;

    public int COMPTE_DE_RESULTAT_B;

    public int PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_DE_GESTION;

    public int PRODUITS_EXCEPTIONNELS_SUR_OPERATIONS_EN_CAPITAL;

    public int TOTAL_DES_PRODUITS_EXCEPTIONNELS_VII;

    public int CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_DE_GESTION;

    public int CHARGES_EXCEPTIONNELLES_SUR_OPERATIONS_EN_CAPITAL;

    public int DOTATIONS_EXCEPTIONNELLES_AUX_AMORTISSEMENTS_ET_PROVISIONS;

    public int TOTAL_DES_CHARGES_EXCEPTIONNELLES_VIII;

    public int RESULTAT_EXCEPTIONNEL_VII_VIII;

    public int PARTICIPATION_DES_SALARIES_AUX_RESULTATS_DE_L_ENTREPRISE;

    public int IMPOTS_SUR_LES_BENEFICES_X;

    public int TOTAL_DES_PRODUITS_I_III_V_VII;

    public int TOTAL_DES_CHARGES_II_IV_VI_VIII_IX_X;

    public int BENEFICE_OU_PERTE_TOTAL_DES_PRODUITS_TOTAL_DES_CHARGES;

    public int RENVOIS_CREDITBAIL_MOBILIER;

    public int RENVOIS_CREDITBAIL_IMMOBILIER;

    public int RENVOIS_TRANSFERT_DE_CHARGES;

    public int RENVOIS_COTISATIONS_PERSONNELLES_DE_L_EXPLOITANT;

    public int RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_PRODUITS;

    public int RENVOIS_REDEVANCES_POUR_CONCESSIONS_DE_BREVETS_DE_LICENCES_CHARGES;

    public int IMMOBILISATIONS;

    public int ACQUISITIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

    public int ACQUISITIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;

    public int ACQUISITIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;

    public int ACQUISITIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;

    public int ACQUISITIONS_TOTAL_GENERAL;

    public int DIMINUTIONS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

    public int DIMINUTIONS_TOTAL_DONT_AUTRES_POSTES_D_IMMOBILISATIONS_INCORPORELLES;

    public int DIMINUTIONS_VIREMENT_POSTES_IMMOBILISATIONS_CORPORELLES_EN_COURS;

    public int DIMINUTIONS_VIREMENT_POSTES_AVANCES_ET_ACOMPTES;

    public int DIMINUTIONS_TOTAL_IMMOBILISATIONS_CORPORELLES;

    public int DIMINUTIONS_PRETS_ET_IMMOBILISATIONS_FINANCIERES;

    public int DIMINUTIONS_TOTAL_IMMOBILISATIONS_FINANCIERES;

    public int DIMINUTIONS_TOTAL_GENERAL;

    public int AMORTISSEMENTS;

    public int AMORTISSEMENTS_FRAIS_D_ETABLISSEMENT_ET_DE_DEVELOPPEMENT_OU_DE_RECHERCHE;

    public int AMORTISSEMENTS_TOTAL_DONT_AUTRES_IMMOBILISATIONS_INCORPORELLES;

    public int AMORTISSEMENTS_TOTAL_IMMOBILISATIONS_CORPORELLES;

    public int AMORTISSEMENTS_TOTAL_GENERAL;

    public int MVT_SUR_CHARGES_REP_PRIMES_DE_REMBOURSEMENT_DES_OBLIGATIONS;

    public int PROVISIONS;

    public int AMORTISSEMENTS_DEROGATOIRES;

    public int TOTAL_PROVISIONS_REGLEMENTEES;

    public int PROVISIONS_POUR_LITIGES;

    public int PROVISIONS_POUR_GARANTIES_DONNEES_AUX_CLIENTS;

    public int PROVISIONS_POUR_PERTE_SUR_MARCHES_A_TERME;

    public int PROVISIONS_POUR_AMENDES_ET_PENALITES;

    public int PROVISIONS_POUR_PERTE_DE_CHANGE;

    public int PROVISIONS_POUR_PENSIONS_ET_OBLIGATIONS_SIMILAIRES;

    public int PROVISIONS_POUR_IMPOTS;

    public int PROVISIONS_POUR_RENOUVELLEMENT_DES_IMMOBILISATIONS;

    public int PROVISIONS_POUR_GROS_ENTRETIEN_ET_GRANDES_REVISIONS_OU_GROSSES_REPARATIONS;

    public int PROVISIONS_POUR_CHARGES_SOCIALES_ET_FISCALES_SUR_CONGES_A_PAYER;

    public int AUTRES_PROVISIONS_POUR_RISQUES_ET_CHARGES;

    public int TOTAL_PROVISIONS_POUR_RISQUES_ET_CHARGES;

    public int SUR_IMMOBILISATIONS_INCORPORELLES;

    public int SUR_IMMOBILISATIONS_CORPORELLES;

    public int SUR_IMMOBILISATIONS_TITRES_MIS_EN_EQUIVALENCE;

    public int SUR_IMMOBILISATIONS_TITRES_DE_PARTICIPATION;

    public int SUR_IMMOBILISATIONS_AUTRES_IMMOBILISATIONS_FINANCIERES;

    public int SUR_STOCKS_ET_EN_COURS;

    public int SUR_COMPTES_CLIENTS;

    public int AUTRES_PROVISIONS_POUR_DEPRECIATION;

    public int TOTAL_PROVISIONS_POUR_DEPRECIATION;

    public int TOTAL_GENERAL;

    public int DONT_DOTATIONS_ET_REPRISES_D_EXPLOITATION;

    public int DONT_DOTATIONS_ET_REPRISES_FINANCIERES;

    public int DONT_DOTATIONS_ET_REPRISES_EXCEPTIONNELLES;

    public int CREANCES_ET_DETTES;

    public int CLIENTS_DOUTEUX_OU_LITIGIEUX;

    public int AUTRES_CREANCES_CLIENTS;

    public int PROVISION_POUR_DEPRECIATION_ANTERIEUREMENT_CONSTITUEE;

    public int CREANCES_REPRESENTATIVES_DE_TITRES_PRETES;

    public int PERSONNEL_ET_COMPTES_RATTACHES;

    public int SECURITE_SOCIALE_AUTRES_ORGANISMES_SOCIAUX;

    public int IMPOTS_SUR_LES_BENEFICES;

    public int T_V_A;

    public int AUTRES_IMPOTS_TAXES_VERSEMENTS_ASSIMILES;

    public int DIVERS;

    public int GROUPE_ET_ASSOCIES;

    public int DEBITEURS_DIVERS_DONT_CREANCES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRES;

    public int TOTAL_ETAT_DES_CREANCES;

    public int EMPRUNTS_OBLIGATAIRES_CONVERTIBLES_BRUT_A_UN_AN_AU_PLUS;

    public int AUTRES_EMPRUNTS_OBLIGATAIRES_BRUT_A_UN_AN_AU_PLUS;

    public int EMPRUNTS_A_1_AN_MAXIMUM_A_L_ORIGINE;

    public int EMPRUNTS_A_PLUS_D_1_AN_A_L_ORIGINE;

    public int EMPRUNTS_ET_DETTES_FINANCIERES_DIVERS;

    public int FOURNISSEURS_ET_COMPTES_RATTACHES;

    public int SECURITE_SOCIALE_ET_AUTRES_ORGANISMES_SOCIAUX;

    public int TVA;

    public int OBLIGATIONS_CAUTIONNEES;

    public int AUTRES_IMPOTS_TAXES_ET_ASSIMILES;

    public int AUTRES_DETTES_DONT_DETTES_RELATIVES_A_DES_OPERATIONS_DE_PENSION_DE_TITRE;

    public int DETTE_REPRESENTATIVE_DE_TITRES_EMPRUNTES;

    public int PRODUITS_CONSTATES_D_AVANCE;

    public int TOTAL_ETAT_DES_DETTES;

    public int EMPRUNTS_SOUSCRITS_EN_COURS_D_EXERCICE;

    public int EMPRUNTS_REMBOURSES_EN_COURS_D_EXERCICE;

    public int AFFECTATION_DU_RESULTAT_RENSEIGNEMENTS_DIVERS;

    public int DIVIDENDES;

    public int ENGAGEMENT_DE_CREDITBAIL_MOBILIER;

    public int ENGAGEMENT_DE_CREDITBAIL_IMMOBILIER;

    public int EFFETS_PORTES_A_L_ESCOMPTE_ET_NON_ECHUS;

    public int SOUSTRAITANCE;

    public int LOCATION_CHARGES_LOCATIVES_ET_DE_COPROPRIETE;

    public int PERSONNEL_EXTERIEUR_A_L_ENTREPRISE;

    public int REMUNERATION_D_INTERMEDIAIRES_ET_HONORAIRES_HORS_RETROCESSIONS;

    public int RETROCESSIONS_D_HONORAIRES_COMMISSIONS_ET_COURTAGES;

    public int AUTRES_COMPTES;

    public int TOTAL_DU_POSTE_CORRESPONDANT_A_LA_LIGNE_FW_DU_TABLEAU_NUMERO_2052;

    public int TAXE_PROFESSIONNELLE;

    public int AUTRES_IMPOTS_TAXES_ET_VERSEMENTS_ASSIMILES;

    public int TOTAL_DU_COMPTE_CORRESPONDANT_A_LA_LIGNE_FX_DU_TABLEAU_NUMERO_2052;

    public int MONTANT_DE_LA_TVA_COLLECTEE;

    public int TOTAL_TVA_DEDUCTIBLE_SUR_BIENS_ET_SERVICES;

    public int EFFECTIF_MOYEN_DU_PERSONNEL;

    public int FILIALES_ET_PARTICIPATIONS;

    public AnnualAccountStringHelper(){}
}
